# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopOnRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusRoute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusStop')),
            ],
        ),
        migrations.AddField(
            model_name='busstop',
            name='route',
            field=models.ManyToManyField(through='bus.StopOnRoute', to='bus.BusRoute'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stops',
            field=models.ManyToManyField(through='bus.StopOnRoute', to='bus.BusStop'),
        ),
    ]
