# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
