# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='updateDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 8, 47, 23, 165322, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
