# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20180316_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='stops',
            new_name='stopsId',
        ),
    ]
